inherit_settings: True

# number of households to simulate
#households_sample_size: 200000
households_sample_size: 500

#chunk_size: 4000000000
chunk_size: 0

#trace_hh_id: 662398
# trace_hh_id: 57

# input tables
input_table_list:
  - tablename: households
    filename: households_xborder.csv
    index_col: household_id

  - tablename: persons
    filename: persons_xborder.csv
    index_col: person_id
    rename_columns:
      HHID: household_id
      PERID: person_id

  - tablename: land_use
    filename: mazs_xborder.csv
    index_col: zone_id
    rename_columns:
      MAZ: zone_id
      pop: POP
      MicroAccessTime: TERMINALTIME

  - tablename: tours
    filename: tours_xborder.csv
    index_col: tour_id


# set false to disable variability check in simple_simulate and interaction_simulate
check_for_variability: False

# - shadow pricing global switches

# turn shadow_pricing on and off for all models (e.g. school and work)
# shadow pricing is deprecated for less than full samples
# see shadow_pricing.yaml for additional settings
use_shadow_pricing: False

# turn writing of sample_tables on and off for all models
# (if True, tables will be written if DEST_CHOICE_SAMPLE_TABLE_NAME is specified in individual model settings)
want_dest_choice_sample_tables: False

resume_after: _

models:
  - initialize_landuse
  - initialize_households
  - initialize_tours
  # --- STATIC cache prebuild steps
  # single-process step to create attribute_combination list
  - initialize_los
  # multi-processable step to build STATIC cache
  # (this step is a NOP if cache already exists and network_los.rebuild_tvpb_cache setting is False)
  - initialize_tvpb
  # # ---
  - tour_od_choice
  - tour_scheduling_probabilistic
  - tour_mode_choice_simulate
  - stop_frequency
  - trip_purpose
  - trip_scheduling
  - trip_destination
  - trip_mode_choice
  # - write_trip_matrices
  # - write_tables

output_tables:
  h5_store: False
  action: include
  prefix: final_
  # FIXME sort is an undocumented feature - sorts table by best index or ref_col according to traceable_table_indexes
  sort: True
  tables:
    - checkpoints
    - accessibility
    - land_use
    - households
    - persons
    - tours
    - attribute_combinations

output_summaries:
  tours:
    - tour_mode
    - od_path_set
    - do_path_set
