SAMPLE_SIZE: 30

SAMPLE_SPEC: tour_od_choice_sample.csv
SPEC: tour_od_choice.csv
COEFFICIENTS: tour_od_choice_coeffs.csv

SIMULATE_CHOOSER_COLUMNS:
  - tour_category
  - tour_type

# model-specific logsum-related settings
CHOOSER_ORIG_COL_NAME: &o origin
ALT_DEST_COL_NAME: &d destination

ALT_OD_COL_NAME: tour_od_id

# AFAIK, these column names need to be used bc the trip and tour
# mode choice models use them as hard-coded skim keys
ORIG_COL_NAME: *o
DEST_COL_NAME: *d

# filter to identify potential origin zones from the land use table
ORIG_FILTER: "poe_id == poe_id"  # trick to use pandas query syntax to filter out rows with null-valued poe_id's

OD_CHOICE_SAMPLE_TABLE_NAME: tour_od_location_sample

CHOOSER_TABLE_NAME: tours

SIZE_TERM_SELECTOR: tour_od_choice

CHOOSER_SEGMENT_COLUMN_NAME: tour_type

ORIGIN_ATTR_COLS_TO_USE:
  - poe_id
  - colonia_pop_accessibility

SEGMENTS:
  - work
  - school
  - cargo
  - shop
  - visit
  - other

LOGSUM_SETTINGS: tour_mode_choice
LOGSUM_PREPROCESSOR: preprocessor
