SAMPLE_SPEC: non_mandatory_tour_destination_sample.csv
SPEC: non_mandatory_tour_destination.csv
COEFFICIENTS: non_mandatory_tour_destination_coefficients.csv

SAMPLE_SIZE: 30

SIZE_TERM_SELECTOR: non_mandatory

# we can't use use household income_segment as this will also be set for non-workers
CHOOSER_SEGMENT_COLUMN_NAME: tour_type

# optional (comment out if not desired)
DEST_CHOICE_LOGSUM_COLUMN_NAME: destination_logsum

# comment out DEST_CHOICE_LOGSUM_COLUMN_NAME if saved alt logsum table
DEST_CHOICE_SAMPLE_TABLE_NAME: tour_destination_sample


SEGMENTS:
  - work
  - recreation
  - dining

SIMULATE_CHOOSER_COLUMNS:
  - tour_type
  - home_zone_id
  - origin
  - person_id
  - income
  - tour_count
  - tour_num
  - auto_available
  - number_of_participants
  - visitor_travel_type
  - tour_category
  - special_size_term

LOGSUM_SETTINGS: tour_mode_choice.yaml

# model-specific logsum-related settings
CHOOSER_ORIG_COL_NAME: home_zone_id
ALT_DEST_COL_NAME: alt_dest
IN_PERIOD:
  work: 14
  recreation: 14
  dining: 14
OUT_PERIOD:
  work: 14
  recreation: 14
  dining: 14