# misc settings
tables_dir: configs/visitor/prob_tables
data_dir: data
config_dir: configs/visitor
plot_dir: configs/visitor/figs
plot_figs: True

# Visitor model settings: occupancy rates for hotels, households and share of each that are business visitors
occupancy_rate:
  hotel: 0.7
  household: 0.018
business_percent:
  hotel: 0.3
  household: 0.04

purpose_ids:
  work: 0
  recreate: 1
  dining: 2

# Any necessary data tables from general input data specified here (not preprocessing specific tables)
land_use: land_use.csv

# Visitor data tables specified here
input_data:
  auto_available: visitor_autoAvailable.csv
  income: visitor_income.csv
  party_size: visitor_partySize.csv
  stop_frequency: visitor_stopFrequency.csv
  stop_purpose: visitor_stopPurpose.csv
  tour_TOD: visitor_tourTOD.csv
  segment_frequency:
    business: visitor_businessFrequency.csv
    personal: visitor_personalFrequency.csv
  stop_duration:
    outbound: visitor_outboundStopDuration.csv
    inbound: visitor_inboundStopDuration.csv

# output data
output_fname:
  households: households_visitor.csv
  persons: persons_visitor.csv
  tours: tours_visitor.csv

  # output configs
  tour_scheduling_probs: tour_scheduling_probs.csv
  tour_scheduling_alts: tour_departure_and_duration_alternatives.csv
  stop_frequency_altse: stop_frequency_alternatives.csv
  stop_frequency_coeffs: 'stop_frequency_coefficients_{purpose}.csv'
  stop_frequency_expressions: 'stop_frequency_{purpose}.csv'
  trip_purpose_probs: trip_purpose_probs.csv
  trip_scheduling_probs: trip_scheduling_probs.csv