# misc settings
tables_dir: configs/visitor/prob_tables
data_dir: data
config_dir: configs

# Visitor model settings: occupancy rates for hotels, households and share of each that are business visitors
occupancy_rate:
  hotel: 0.7
  household: 0.018
business_percent:
  hotel: 0.3
  household: 0.04

# Any necessary data tables specified here
land_use: land_use.csv

# Visitor data tables specified here
input_data:
  auto_available: visitor_autoAvailable.csv
  income: visitor_income.csv
  party_size: visitor_partySize.csv
  stop_frequency: visitor_stopFrequency.csv
  stop_purpose: visitor_stopPurpose.csv
  tour_TOD: visitor_tourTOD.csv
  segment_frequency:
    business: visitor_businessFrequency.csv
    personal: visitor_personalFrequency.csv
  stop_duration:
    outbound: visitor_outboundStopDuration.csv
    inbound: visitor_inboundStopDuration.csv

# output data
output_data:
  mazs_output_fname: mazs_xborder.csv
  households_output_fname: households_xborder.csv
  persons_output_fname: persons_xborder.csv
  tours_output_fname: tours_xborder.csv
  tap_lines_output_fname: tap_lines.csv
  taps_output_fname: taps.csv

  # output configs
  tour_scheduling_probs_output_fname: tour_scheduling_probs.csv
  tour_scheduling_alts_output_fname: tour_departure_and_duration_alternatives.csv
  stop_frequency_alts_output_fname: stop_frequency_alternatives.csv
  stop_frequency_coeffs_output_formattable_fname: 'stop_frequency_coefficients_{purpose}.csv'
  stop_frequency_expressions_output_formattable_fname: 'stop_frequency_{purpose}.csv'
  trip_purpose_probs_output_fname: trip_purpose_probs.csv
  trip_scheduling_probs_output_fname: trip_scheduling_probs.csv