LOGIT_TYPE: MNL
SEGMENT_COL: primary_purpose
SPEC_SEGMENTS:
- COEFFICIENTS: stop_frequency_coefficients_work.csv
  SPEC: stop_frequency_work.csv
  primary_purpose: work
- COEFFICIENTS: stop_frequency_coefficients_recreation.csv
  SPEC: stop_frequency_recreation.csv
  primary_purpose: recreation
- COEFFICIENTS: stop_frequency_coefficients_dining.csv
  SPEC: stop_frequency_dining.csv
  primary_purpose: dining
preprocessor:
  DF: tours_merged
  SPEC: trip_frequency_annotate_tours_preprocessor
