inherit_settings: True

multiprocess: True
#households_sample_size: 1000
num_processes: 20

chunk_training_mode: disabled

# raise error if any sub-process fails without waiting for others to complete
# (Shadow pricing requires fail_fast setting in multiprocessing mode)
fail_fast: True

trace_hh_id:

resume_after: 

models:
   - initialize_landuse
   - initialize_households
   - compute_accessibility
   - initialize_los
   - external_student_identification
   - external_worker_identification
   - external_school_location
   - external_workplace_location
   - school_location
   - workplace_location
   - work_from_home
   - auto_ownership_simulate
   - vehicle_type_choice
   - transponder_ownership
   - free_parking
   - telecommute_frequency
   - cdap_simulate
   - mandatory_tour_frequency
   - mandatory_tour_scheduling
   - joint_tour_frequency
   - external_joint_tour_identification
   - joint_tour_composition
   - joint_tour_participation
   - joint_tour_destination
   - external_joint_tour_destination
   - joint_tour_scheduling
   - non_mandatory_tour_frequency
   - external_non_mandatory_identification
   - non_mandatory_tour_destination
   - external_non_mandatory_destination
   - non_mandatory_tour_scheduling
   - vehicle_allocation
   - tour_mode_choice_simulate
   - atwork_subtour_frequency
   - atwork_subtour_destination
   - atwork_subtour_scheduling
   - atwork_subtour_mode_choice
   - stop_frequency
   - trip_purpose
   - trip_destination
   - trip_purpose_and_destination
   - trip_scheduling
   - trip_mode_choice
  - write_data_dictionary
  - track_skim_usage
  - write_trip_matrices
  - write_tables

multiprocess_steps:
  - name: mp_initialize
    begin: initialize_landuse
  - name: mp_accessibility
    begin: compute_accessibility
    num_processes: 10
    slice:
      tables:
        - accessibility
  - name: mp_los
    begin: initialize_los
  - name: mp_models
    begin: school_location
    slice:
      tables:
        - households
        - persons
  - name: mp_summarize
    begin: write_data_dictionary
