#inherit_settings: True

# - tracing

# trace household id; comment out or leave empty for no trace
# households with all tour types
trace_hh_id: 13163

# trace origin, destination in accessibility calculation; comment out or leave empty for no trace
#trace_od:

households_sample_size: 20

# input tables
input_table_list:
  - tablename: households
    filename: households.csv
    index_col: household_id
    rename_columns:
      hhid: household_id
      persons: hhsize
      hworkers: num_workers
      veh: auto_ownership
      mgra: home_zone_id
      hinc: income
      hht: HHT
    keep_columns:
      - home_zone_id
      - income
      - hhsize
      - HHT
      - auto_ownership
      - num_workers
  - tablename: persons
    filename: persons.csv
    index_col: person_id
    rename_columns:
      PERID: person_id
    rename_columns:
      hhid: household_id
      perid: person_id
      pnum: PNUM
    keep_columns:
      - household_id
      - age
      - PNUM
      - sex
      - pemploy
      - pstudent
      - ptype
  - tablename: land_use
    filename: land_use.csv
    index_col: zone_id
    rename_columns:
      MAZ: zone_id
      # COUNTY: county_id
    # keep_columns:
      # - TAZ
      # - DISTRICT
      # - SD
      # - county_id
      # - TOTHH
      # - TOTPOP
      # - TOTACRE
      # - RESACRE
      # - CIACRE
      # - TOTEMP
      # - AGE0519
      # - RETEMPN
      # - FPSEMPN
      # - HEREMPN
      # - OTHEMPN
      # - AGREMPN
      # - MWTEMPN
      # - PRKCST
      # - OPRKCST
      # - area_type
      # - HSENROLL
      # - COLLFTE
      # - COLLPTE
      # - TOPOLOGY
      # - TERMINAL
      # - access_dist_transit

output_tables:
  h5_store: False
  action: include
  prefix: final_
  sort: True
  tables:
    - checkpoints
    - accessibility
    - land_use
    - households
    - persons
    - tours
    - trips
    - joint_tour_participants
    - vehicles

distributed_time_factor_work_mean: 1.0
distributed_time_factor_work_stddev: 0.7
distributed_time_factor_nonwork_mean: 1.0
distributed_time_factor_nonwork_stddev: 0.6
distributed_time_factor_min: 0.1
distributed_time_factor_max: 10

resume_after: 

models:
  - initialize_landuse
  - initialize_households
  - compute_accessibility
  # --- STATIC cache prebuild steps
  # single-process step to create attribute_combination list
  - initialize_los
  # multi-processable step to build STATIC cache
  - external_student_identification
  - external_worker_identification
  - external_school_location
  - external_workplace_location
  - school_location
  - workplace_location
  - work_from_home
  - auto_ownership_simulate
  - vehicle_type_choice
  - transponder_ownership
  - free_parking
  - telecommute_frequency
  - cdap_simulate
  - mandatory_tour_frequency
  - mandatory_tour_scheduling
  - joint_tour_frequency
  - external_joint_tour_identification
  - joint_tour_composition
  - joint_tour_participation
  - joint_tour_destination
  - external_joint_tour_destination
  - joint_tour_scheduling
  - non_mandatory_tour_frequency
  - external_non_mandatory_identification
  - non_mandatory_tour_destination
  - external_non_mandatory_destination
  - non_mandatory_tour_scheduling
  - vehicle_allocation
  - tour_mode_choice_simulate
  - atwork_subtour_frequency
  - atwork_subtour_destination
  - atwork_subtour_scheduling
  - atwork_subtour_mode_choice
  - stop_frequency
  - trip_purpose
  - trip_destination
  - trip_purpose_and_destination
  - trip_scheduling
  - trip_mode_choice
  - write_data_dictionary
  - track_skim_usage
  - write_trip_matrices
  - write_tables
