inherit_settings: settings.yaml

multiprocess: True
households_sample_size: 1000
num_processes: 24

chunk_training_mode: disabled

# raise error if any sub-process fails without waiting for others to complete
# (Shadow pricing requires fail_fast setting in multiprocessing mode)
fail_fast: True

resume_after:

models:
  - initialize_landuse
  - initialize_households
  - compute_accessibility
  # --- STATIC cache prebuild steps
  # single-process step to create attribute_combination list
  - initialize_los
  # multi-processable step to build STATIC cache
  # (this step is a NOP if cache already exists and network_los.rebuild_tvpb_cache setting is False)
  - initialize_tvpb
  # ---
  # - external_worker_student_identification
  - school_location
  - workplace_location
  - auto_ownership_simulate
  - free_parking
  - cdap_simulate
  - mandatory_tour_frequency
  - mandatory_tour_scheduling
  - joint_tour_frequency
  - joint_tour_composition
  - joint_tour_participation
  - joint_tour_destination
  - joint_tour_scheduling
  - non_mandatory_tour_frequency
  - non_mandatory_tour_destination
  - non_mandatory_tour_scheduling
  - tour_mode_choice_simulate
  - atwork_subtour_frequency
  - atwork_subtour_destination
  - atwork_subtour_scheduling
  - atwork_subtour_mode_choice
  - stop_frequency
  - trip_purpose
  - trip_destination
  - trip_purpose_and_destination
  - trip_scheduling
  - trip_mode_choice
  - write_data_dictionary
  - track_skim_usage
  - write_trip_matrices
  - write_tables

multiprocess_steps:
  - name: mp_initialize
    begin: initialize_landuse
  - name: mp_accessibility
    begin: compute_accessibility
    num_processes: 20
    slice:
      tables:
        - accessibility
  - name: mp_los
    begin: initialize_los
  - name: mp_tvpb
    begin: initialize_tvpb
    num_processes: 5
    slice:
      tables:
        - attribute_combinations
  - name: mp_models
    begin: school_location
    slice:
      tables:
        - households
        - persons
  - name: mp_summarize
    begin: write_data_dictionary
