LOGIT_TYPE: NL
#LOGIT_TYPE: MNL

tvpb_mode_path_types:
  WALK_TRANSIT:
    od: WTW
    do: WTW
  PNR_TRANSIT:
    od: PTW
    do: WTP
  KNR_TRANSIT:
    od: KTW
    do: WTK
  TNC_TRANSIT:
    od: NTW
    do: WTN

NESTS:
  name: root
  coefficient: coef_nest_root
  alternatives:
      - name: AUTO
        coefficient: coef_nest_AUTO
        alternatives:
            - DRIVEALONE
            - SHARED2
            - SHARED3
      - name: NONMOTORIZED
        coefficient: coef_nest_NONMOTORIZED
        alternatives:
          - WALK
          - BIKE
      - name: TRANSIT
        coefficient: coef_nest_TRANSIT
        alternatives:
          - WALK_TRANSIT
          - PNR_TRANSIT
          - KNR_TRANSIT
          - TNC_TRANSIT
      - name: RIDEHAIL
        coefficient: coef_nest_RIDEHAIL
        alternatives:
          - TAXI
          - TNC_SINGLE
          - TNC_SHARED
      - name: SCHOOL_BUS
        coefficient: coef_nest_SCHOOL_BUS
        alternatives:
          - SCH_BUS

SPEC: tour_mode_choice.csv
COEFFICIENTS: tour_mode_choice_coefficients.csv
COEFFICIENT_TEMPLATE: tour_mode_choice_coefficients_template.csv

# so far, we can use the same spec as for non-joint tours
preprocessor:
  SPEC: tour_mode_choice_annotate_choosers_preprocessor
  DF: choosers
  TABLES:
    - land_use
    - tours
    - vehicles
    - households

nontour_preprocessor:
  SPEC: tour_mode_choice_annotate_choosers_preprocessor
  DF: choosers
  TABLES:
    - land_use

annotate_tours:
  SPEC: annotate_tours_tour_mode_choice
  DF: choosers
  TABLES:
    - tours


# to reduce memory needs filter chooser table to these fields
LOGSUM_CHOOSER_COLUMNS:
  - tour_type
  - hhsize
  - density_index
  - age
  - age_16_p
  - age_16_to_19
  - auto_ownership
  - num_adults
  - sex
  - ptype
  - number_of_participants
  - tour_category
  - num_workers
  - value_of_time
  - free_parking_at_work
  - income_segment
  - demographic_segment
  - c_ivt_for_segment
  - c_cost_for_segment
  - income
  - time_factor_work
  - time_factor_nonwork
  - duration

MODE_CHOICE_LOGSUM_COLUMN_NAME: mode_choice_logsum
